In [1]:
import sympy
from sympy import Matrix
import numpy as np


In [2]:
%matplotlib notebook
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

# Linear algebra

## Session 03: solving systems of linear equations

## Gerhard Jäger

### May 11, 2022

## Matrices with python and numpy

- vector

In [4]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

- matrix

In [5]:
A = np.array([
    [1,2, 3],
    [4,5,6],
    [7,8,9]
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## vector algebra

In [6]:
y = np.array([3,10,4])

x + y

array([ 4, 12,  7])

In [7]:
3*x

array([3, 6, 9])

In [8]:
2*x - 3*y

array([ -7, -26,  -6])

applying a matrix to a vector

In [9]:
A, x

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 2, 3]))

In [11]:
A @ x

array([14, 32, 50])

matrix transposition

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

matrix multiplication

In [14]:
B = np.array([
    [4,1,0],
    [1,0,2],
    [4,5,6]
])

In [15]:
A, B

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[4, 1, 0],
        [1, 0, 2],
        [4, 5, 6]]))

In [16]:
A @ B

array([[18, 16, 22],
       [45, 34, 46],
       [72, 52, 70]])

identity matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

diagonal matrix

In [18]:
np.diag([2,3, 4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

inverse matrix

In [19]:
A = np.array(
[
    [1, -4, 2],
    [-2, 1, 3],
    [2,6,8]
])
A

array([[ 1, -4,  2],
       [-2,  1,  3],
       [ 2,  6,  8]])

In [20]:
try:
    print(np.linalg.inv(A))
except:
    print("Matrix is not invertible!")

[[ 0.07936508 -0.34920635  0.11111111]
 [-0.17460317 -0.03174603  0.05555556]
 [ 0.11111111  0.11111111  0.05555556]]


In [21]:
B = np.array(
[
    [1, -4, 2],
    [-2, 1, 3],
    [2,6,-10]
])

In [22]:
B

array([[  1,  -4,   2],
       [ -2,   1,   3],
       [  2,   6, -10]])

In [27]:
try:
    print(np.linalg.inv(B))
except:
    print("Matrix is not invertible!")

Matrix is not invertible!


## Python and SymPy


In [29]:
import sympy
from sympy import Matrix

- creating a vector

In [30]:
x = Matrix([1,2,3])
x

Matrix([
[1],
[2],
[3]])

- creating a matrix

In [31]:
A = Matrix(
[
    [1,2, 3],
    [4,5,6],
    [7,8,9]
])
A

Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

### vector algebra

In [32]:
y = Matrix([3,10,4])
y

Matrix([
[ 3],
[10],
[ 4]])

In [33]:
x+y

Matrix([
[ 4],
[12],
[ 7]])

In [34]:
3*x

Matrix([
[3],
[6],
[9]])

In [35]:
2 * x - 3 * y

Matrix([
[ -7],
[-26],
[ -6]])

applying a vector to a matrix

In [36]:
A * x

Matrix([
[14],
[32],
[50]])

matrix transposition

In [ ]:
A.T

matrix multiplication

In [ ]:
B = Matrix(
[
    [4,1,0],
    [1,0,2],
    [4,5,6]
])
B

In [37]:
A * B

Matrix([
[3, 16, -22],
[6, 25, -37],
[9, 34, -52]])

identity matrix

In [38]:
sympy.eye(3)

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

diagonal matrix

In [41]:
sympy.diag(1,2,3)

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

matrix inverse

In [42]:
A = Matrix(
[
    [1, -4, 2],
    [-2, 1, 3],
    [2,6,8]
])
A

Matrix([
[ 1, -4, 2],
[-2,  1, 3],
[ 2,  6, 8]])

In [44]:
try:
    print(sympy.pretty(A.inv()))
except:
    print("Matrix is not invertible!")

⎡      -22        ⎤
⎢5/63  ────   1/9 ⎥
⎢       63        ⎥
⎢                 ⎥
⎢-11              ⎥
⎢────  -2/63  1/18⎥
⎢ 63              ⎥
⎢                 ⎥
⎣1/9    1/9   1/18⎦


In [45]:
B = Matrix(
[
    [1, -4, 2],
    [-2, 1, 3],
    [2,6,-10]
])
B

Matrix([
[ 1, -4,   2],
[-2,  1,   3],
[ 2,  6, -10]])

In [47]:
try:
    print(sympy.pretty(B.inv()))
except:
    print("Matrix is not invertible!")

Matrix is not invertible!


### Symbolic computation with SymPy

The real strength of Sympy is that it can calculate with variables as well as with numbers.



In [48]:
from sympy import symbols
a,b,c,d = symbols('a b c d')

In [49]:
A = Matrix([
    [a, b],
    [c,d]
])
A

Matrix([
[a, b],
[c, d]])

In [50]:
A.inv()

Matrix([
[ d/(a*d - b*c), -b/(a*d - b*c)],
[-c/(a*d - b*c),  a/(a*d - b*c)]])

## Back to solving systems of linear equations

### First part: lower elimination

$$
\begin{array}{rrrrrrr}
    3x &+ &4y &- &z &=& 0\\
       &  &y  &+ &z &=& 4\\
     x & - &y &- & z & =&-5\\
\end{array}
$$

- subtracting $\frac{1}{3}$ times the first equation from the third equation:

$$
\begin{array}{rrrrrrr}
    3x &+& 4y &-& z &=& 0\\
        && y &+& z &=& 4\\
     &-&\frac{7}{3} y &-& \frac{2}{3}z &=& -5
\end{array}
$$

- adding $\frac{7}{3}$ times the second equation to the third equation:

$$
\begin{array}{rrrrrrr}
    3x &+& 4y &-& z &=& 0\\
      &&   y &+& z &=& 4\\
     &&&& \frac{5}{3}z &=& \frac{13}{3}
\end{array}
$$

**Lower elimination** is completed if the left-hand side has a **upper triangular** shape.

### Second part: lower elimination

In the elimination part, we transformed all coefficients below the diagonal to 0.
In the substitution part, we successively transform all coefficients **above** the diagonal to 0.

- subtract $\frac{3}{5}$ times third equation from second equation.


$$
\begin{array}{rrrrrrr}
    3x &+& 4y &-& z &=& 0\\
      &&   y &&  &=& \frac{7}{5}\\
     &&&& \frac{5}{3}z &=& \frac{13}{3}
\end{array}
$$


- add $\frac{3}{5}$ times third equation to first equation.


$$
\begin{array}{rrrrrrr}
    3x &+& 4y &&  &=& \frac{13}{5}\\
      &&   y &&  &=& \frac{7}{5}\\
     &&&& \frac{5}{3}z &=& \frac{13}{3}
\end{array}
$$


- subtract 4 times second equation from first equation.


$$
\begin{array}{rrrrrrr}
    3x &&  &&  &=& -3\\
      &&   y &&  &=& \frac{7}{5}\\
     &&&& \frac{5}{3}z &=& \frac{13}{3}
\end{array}
$$

### Third step: dividing by pivots

The diagonal coefficients are called the **pivots**. In the last step, we transform them into 1.

- divide first equation by 3


$$
\begin{array}{rrrrrrr}
    x &&  &&  &=& -1\\
      &&   y &&  &=& \frac{7}{5}\\
     &&&& \frac{5}{3}z &=& \frac{13}{3}
\end{array}
$$


- divide third equation by $\frac{5}{3}$


$$
\begin{array}{rrrrrrr}
    x &&  &&  &=& -1\\
      &&   y &&  &=& \frac{7}{5}\\
     &&&& z &=& \frac{13}{5}
\end{array}
$$

#### checking result


$$
\begin{array}{rrrrrrr}
    3x &+ &4y &- &z &=& 0\\
       &  &y  &+ &z &=& 4\\
     x & - &y &- & z & =&-5\\
\end{array}
$$

becomes

$$
\begin{array}{rrrrrrr}
    -3 &+ &4\frac{7}{5} &- &\frac{13}{5} &=& 0\\
       &  &\frac{7}{5}  &+ &\frac{13}{5} &=& 4\\
     x & - &\frac{7}{5} &- & \frac{13}{5} & =&-5\\
\end{array}
$$

Stripping down the superfluous notation, this is a sequence of **augmented matrices**. The augmented matrix is the matrix of coefficients on the left-hand side, plus the right-hand side as additional column.

- system of equations in matrix notation
$$
\begin{aligned}
A &= \begin{bmatrix}
3 & 4 & -1\\
0 & 1 & 1\\
1 & -1 & -1
\end{bmatrix}\\[1em]
\mathbf x &= \begin{bmatrix}
x\\y\\z
\end{bmatrix}\\[1em]
\mathbf b &= \begin{bmatrix}
0\\4\\-5
\end{bmatrix}\\[1em]
A\mathbf x &= \mathbf b
\end{aligned}
$$



- augmented matrix

$$
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
1 & -1 & -1&-5
\end{array}
\right]
$$

### lower elimination: transforming below-diagonal entries to 0

- subtracting $\frac{1}{3}$ times first row from third row


$$
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
0 & -\frac{7}{3} & -\frac{2}{3} &-5
\end{array}
\right]
$$


- adding $\frac{7}{3}$ times second row to third row


$$
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
$$

### upper elimination: transforming above-diagonal entries to 0


- subtract $\frac{3}{5}$ times third row from second row


$$
\left[
\begin{array}{rrr|r}
3 & 4 & -1 &0  \\
0 & 1 & 0  & \frac{7}{5} \\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
$$

- add $\frac{3}{5}$ times third row to first row


$$
\left[
\begin{array}{rrr|r}
3 & 4 & 0 & \frac{13}{5}  \\
0 & 1 & 0  & \frac{7}{5} \\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
$$

- subtract 4 times second row from first row


$$
\left[
\begin{array}{rrr|r}
3 & 0 & 0 & -3  \\
0 & 1 & 0  & \frac{7}{5} \\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
$$

## dividing by pivots



$$
\left[
\begin{array}{rrr|r}
1 & 0 & 0 & -1  \\
0 & 1 & 0  & \frac{7}{5} \\
0 & 0 & 1 &\frac{13}{5}
\end{array}
\right]
$$

All these steps can be formalized as multiplication with some matrix.

- subtracting $\frac{1}{3}$ times first row from third row


$$
\begin{aligned}
E_{3,1}
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
1 & -1 & -1&-5
\end{array}
\right] &= 
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
0 & -\frac{7}{3} & \frac{2}{3} &-5
\end{array}
\right]
\end{aligned}
$$


$$
E_{3,1} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
-\frac{1}{3} & 0 & 1
\end{bmatrix}
$$

- adding $\frac{7}{3}$ times second row to third row

$$
\begin{aligned}
E_{3,2}
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
0 & -\frac{7}{3} & -\frac{2}{3} &-5
\end{array}
\right]
&= 
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
\end{aligned}
$$

$$
E_{3,2} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0&\frac{7}{3} & 1
\end{bmatrix}
$$

- subtract $\frac{3}{5}$ times third row from second row


$$
\begin{aligned}
E_{2,3}
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
&= 
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 0&\frac{7}{5}\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
\end{aligned}
$$

$$
E_{2,3} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & -\frac{3}{5}\\
0&0 & 1
\end{bmatrix}
$$

- add $\frac{3}{5}$ times third row to first row


$$
\begin{aligned}
E_{1,3}
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 0&\frac{7}{5}\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
&= 
\left[
\begin{array}{rrr|r}
3 & 4 & 0&\frac{13}{5}\\
0 & 1 & 0&\frac{7}{5}\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
\end{aligned}
$$

$$
E_{1,3} = \begin{bmatrix}
1 & 0 & \frac{3}{5}\\
0 & 1 & 0\\
0&0 & 1
\end{bmatrix}
$$

- subtract 4 times second row from first row


$$
\begin{aligned}
E_{1,2}
\left[
\begin{array}{rrr|r}
3 & 4 & 0&\frac{13}{5}\\
0 & 1 & 0&\frac{7}{5}\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
&= 
\left[
\begin{array}{rrr|r}
3 & 0 & 0&-3\\
0 & 1 & 0&\frac{7}{5}\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
\end{aligned}
$$

$$
E_{1,2} = \begin{bmatrix}
1 & -4 & 0\\
0 & 1 & 0\\
0&0 & 1
\end{bmatrix}
$$

- divide each row by its pivot

$$
D\left[
\begin{array}{rrr|r}
3 & 0 & 0&-3\\
0 & 1 & 0&\frac{7}{5}\\
0 & 0 & \frac{5}{3} &\frac{13}{3}
\end{array}
\right]
=
\left[
\begin{array}{rrr|r}
1 & 0 & 0&-1\\
0 & 1 & 0&\frac{7}{5}\\
0 & 0 & 1 &\frac{13}{5}
\end{array}
\right]
$$

$$
D = \begin{bmatrix}
\frac{1}{3} & 0 & 0\\
0 & 1 & 0\\
0 & 0 & \frac{3}{5}
\end{bmatrix}
$$

Let us reflect what we did. Taking everyting together, we have

$$
\begin{aligned}
D E_{1,2} E_{1,3} E_{2,3} E_{3,2} E_{3,1} A & = \mathbf I\\
D E_{1,2} E_{1,3} E_{2,3} E_{3,2} E_{3,1} \mathbf b & = \mathbf x\\
\end{aligned}
$$

Therefore
$$\Large
\begin{aligned}
D E_{1,2} E_{1,3} E_{2,3} E_{3,2} E_{3,1}  & = A^{-1}\\
\end{aligned}
$$

Let's check this with SymPy.

In [51]:
from sympy import Rational, diag

In [52]:
A = Matrix([
    [3,4,-1],
    [0,1,1],
    [1,-1,-1]
])
A

Matrix([
[3,  4, -1],
[0,  1,  1],
[1, -1, -1]])

In [53]:
b = Matrix([0, 4, -5])
b

Matrix([
[ 0],
[ 4],
[-5]])

In [54]:
E31 = Matrix(
[
    [1, 0, 0],
    [0, 1, 0],
    [-Rational(1,3), 0, 1]
])
E31

Matrix([
[   1, 0, 0],
[   0, 1, 0],
[-1/3, 0, 1]])

In [55]:
E32 = Matrix([
    [1,0,0],
    [0,1,0],
    [0,Rational(7,3),1]
])
E32

Matrix([
[1,   0, 0],
[0,   1, 0],
[0, 7/3, 1]])

In [56]:
E23 = Matrix([
    [1,0,0],
    [0,1,-Rational(3,5)],
    [0,0,1]
])
E23

Matrix([
[1, 0,    0],
[0, 1, -3/5],
[0, 0,    1]])

In [57]:
E13 = Matrix([
    [1,0,Rational(3,5)],
    [0,1,0],
    [0,0,1]
])
E13

Matrix([
[1, 0, 3/5],
[0, 1,   0],
[0, 0,   1]])

In [58]:
E12 = Matrix([
    [1,-4,0],
    [0,1,0],
    [0,0,1]
])
E12

Matrix([
[1, -4, 0],
[0,  1, 0],
[0,  0, 1]])

In [59]:
D = diag(Rational(1,3), 1, Rational(3,5))
D

Matrix([
[1/3, 0,   0],
[  0, 1,   0],
[  0, 0, 3/5]])

In [60]:
D * E12 * E13 * E23 * E32 * E31 * A

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [61]:
D * E12 * E13 * E23 * E32 * E31 * b

Matrix([
[  -1],
[ 7/5],
[13/5]])

In [62]:
D * E12 * E13 * E23 * E32 * E31

Matrix([
[   0,    1,    1],
[ 1/5, -2/5, -3/5],
[-1/5,  7/5,  3/5]])

In [63]:
A.inv()

Matrix([
[   0,    1,    1],
[ 1/5, -2/5, -3/5],
[-1/5,  7/5,  3/5]])

So we can compute the inverse of a square matrix by multiplying out the elimination matrices.

There is also a shorter way to the inverse matrix: augment $A$ with the identity matrix!

$$
\begin{aligned}
A\begin{bmatrix}
\mathbf x_1 & \mathbf x_2 & \mathbf x_3
\end{bmatrix} & = \mathbf I\\
\vdots & \vdots & \vdots\\
D E_{1,2} E_{1,3} E_{2,3} E_{3,2} E_{3,1} A\begin{bmatrix}
\mathbf x_1 & \mathbf x_2 & \mathbf x_3
\end{bmatrix} & = D E_{1,2} E_{1,3} E_{2,3} E_{3,2} E_{3,1}\mathbf I\\
A^{-1} A\begin{bmatrix}
\mathbf x_1 & \mathbf x_2 & \mathbf x_3
\end{bmatrix} & = A^{-1}\mathbf I\\
\begin{bmatrix}
\mathbf x_1 & \mathbf x_2 & \mathbf x_3
\end{bmatrix} & = A^{-1}\\
\end{aligned}
$$

- augmented matrix:
    
$$
\left[
\begin{array}{rrr|rrr}
3 & 4  & -1 & 1 & 0 & 0\\
0 & 1  & 1  & 0 & 1 & 0\\
1 & -1 & -1 & 0 & 0 & 1
\end{array}
\right]
$$

- left-multiplication with $E_{3,1}$:

$$
\left[
\begin{array}{rrr|rrr}
3 & 4  & -1 & 1 & 0 & 0\\
0 & 1  & 1  & 0 & 1 & 0\\
0  & -\frac{7}{3} & -\frac{2}{3} & -\frac{1}{3} & 0 & 1
\end{array}
\right]
$$


- left-multiplication with $E_{3,2}$:

$$
\left[
\begin{array}{rrr|rrr}
3 & 4  & -1 & 1 & 0 & 0\\
0 & 1  & 1  & 0 & 1 & 0\\
0  & 0 & \frac{5}{3} & -\frac{1}{3} & \frac{7}{3} & 1
\end{array}
\right]
$$


- left-multiplication with $E_{2,3}$:

$$
\left[
\begin{array}{rrr|rrr}
3 & 4  & -1          & 1            & 0            & 0\\
0 & 1  &  0          & \frac{1}{5}  & -\frac{2}{5} & -\frac{3}{5}\\
0 & 0  & \frac{5}{3} & -\frac{1}{3} & \frac{7}{3}  & 1
\end{array}
\right]
$$


- left-multiplication with $E_{1,3}$:

$$
\left[
\begin{array}{rrr|rrr}
3 & 4  & 0           & \frac{4}{5}  & \frac{7}{5}  & \frac{3}{5}\\
0 & 1  &  0          & \frac{1}{5}  & -\frac{2}{5} & -\frac{3}{5}\\
0 & 0  & \frac{5}{3} & -\frac{1}{3} & \frac{7}{3}  & 1
\end{array}
\right]
$$


- left-multiplication with $E_{1,2}$:

$$
\left[
\begin{array}{rrr|rrr}
3 & 0  & 0           & 0            & 3            & 3\\
0 & 1  &  0          & \frac{1}{5}  & -\frac{2}{5} & -\frac{3}{5}\\
0 & 0  & \frac{5}{3} & -\frac{1}{3} & \frac{7}{3}  & 1
\end{array}
\right]
$$


- left-multiplication with D:

$$
\begin{aligned}
&\left[
\begin{array}{rrr|rrr}
1 & 0  & 0 & 0            & 1            & 1\\
0 & 1  & 0 & \frac{1}{5}  & -\frac{2}{5} & -\frac{3}{5}\\
0 & 0  & 1 & -\frac{1}{5} & \frac{7}{5}  & \frac{3}{5}
\end{array}
\right]\\[1em]
A^{-1} &= 
\left[
\begin{array}{rrr}
  0            & 1            & 1\\
 \frac{1}{5}  & -\frac{2}{5} & -\frac{3}{5}\\
 -\frac{1}{5} & \frac{7}{5}  & \frac{3}{5}
\end{array}
\right]
\end{aligned}
$$


### Algorithm to find the inverse of a square matrix $A$ (preliminary)

(@ represents matrix multiplication.)

<img src="_img/pseudocode.svg" width="500">

## Permutation

The algorithm fails if a 0 occurs at the diagonal somewhere along the way. Sometimes, this is benign, sometimes not.

Here is a benign example:

$$
A =  \begin{bmatrix}
    1 & 1 & 1\\
    1 & 1 & -1\\
    1 & -1 & 1
\end{bmatrix}
$$

This matrix is invertible, according to SymPy:

In [64]:
A = Matrix([
    [1,1,1],
    [1,1,-1],
    [1,-1,1]
])
A

Matrix([
[1,  1,  1],
[1,  1, -1],
[1, -1,  1]])

In [65]:
A.inv()

Matrix([
[  0,  1/2,  1/2],
[1/2,    0, -1/2],
[1/2, -1/2,    0]])

Still, elimination fails:
    
  
$$
\left[
\begin{array}{rrr|rrr}
1 & 1  & 1 & 1 & 0 & 0\\
1 & 1  & -1  & 0 & 1 & 0\\
1 & -1 & 1 & 0 & 0 & 1
\end{array}
\right]
$$

- subtracting first row from second:
$$
\left[
\begin{array}{rrr|rrr}
1 & 1  & 1  & 1  & 0 & 0\\
0 & 0  & -2 & -1 & 1 & 0\\
1 & -1 & 1  & 0  & 0 & 1
\end{array}
\right]
$$


- subtracting first row from third:
$$
\left[
\begin{array}{rrr|rrr}
1 & 1  & 1  & 1  & 0 & 0\\
0 & 0  & -2 & -1 & 1 & 0\\
0 & -2 & 0  & -1 & 0 & 1
\end{array}
\right]
$$


Now, according to the algorithm, we have to subtract $l$ times the second row from the third, with

$$
l = \frac{-2}{0}
$$

This is not possible. We can recover from this though, by replacing the second and third row:

$$
\left[
\begin{array}{rrr|rrr}
1 & 1  & 1  & 1  & 0 & 0\\
0 & -2 & 0  & -1 & 0 & 1\\
0 & 0  & -2 & -1 & 1 & 0\\
\end{array}
\right]
$$



The rest is straightforward:

- add $\frac{1}{2}$ times third row to first row:

$$
\left[
\begin{array}{rrr|rrr}
1 & 1  & 0  & \frac{1}{2}  & \frac{1}{2} & 0\\
0 & -2 & 0  & -1 & 0 & 1\\
0 & 0  & -2 & -1 & 1 & 0\\
\end{array}
\right]
$$

- add $\frac{1}{2}$ times second row to first row:

$$
\left[
\begin{array}{rrr|rrr}
1 & 0  & 0  & 0  & \frac{1}{2} & \frac{1}{2}\\
0 & -2 & 0  & -1 & 0 & 1\\
0 & 0  & -2 & -1 & 1 & 0\\
\end{array}
\right]
$$

- divide each row by its pivot

$$
\left[
\begin{array}{rrr|rrr}
1 & 0  & 0  & 0  & \frac{1}{2} & \frac{1}{2}\\
0 & 1 & 0  & \frac{1}{2} & 0 & -\frac{1}{2}\\
0 & 0  & 1 & \frac{1}{2} & -\frac{1}{2} & 0\\
\end{array}
\right]
$$

The step of exchanging the second and third row can also be done via matrix multiplication:

$$
P_{2,3} = \begin{bmatrix}
1 & 0 & 0\\
0 & 0 & 1\\
0 & 1 & 0
\end{bmatrix}
$$

Here we had a configuration where, during lower elimination, a $0$ was in $X_{i,i}$ and a non-zero entry $X_{j,i}$ was below it.

In such a configuration, we can save the day by multiplying everything with $P_{i,j}$ from the left.

If both $X_{i,i}=0$ and $X_{j,i}=0$, we just do nothing and proceed to the next row.

This cannot happen during upper elimination, because it does not affect the diagonal.




### Algorithm to find the inverse of a square matrix $A$ (final version)

(@ represents matrix multiplication.)

<img src="_img/pseudocodeRevised.svg" width="400">

## Systems of linear equation without solution

$$
\begin{aligned}
A &= 
\begin{bmatrix}
3 & 4  & -1\\
0 & 1  & 1\\
0 & -1 & -1
\end{bmatrix}\\[1em]
\mathbf b &= \begin{bmatrix}0 \\ 4 \\ 5\end{bmatrix}
\end{aligned}
$$

## elimination step


$$
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
0 & 0 & 0&-1
\end{array}
\right]
$$

Here we already see that this system cannot have a solution, because the third row has no solution.

## Systems of linear equation with infinitely many solution

$$
\begin{aligned}
A &= 
\begin{bmatrix}
3 & 4  & -1\\
0 & 1  & 1\\
0 & -1 & -1
\end{bmatrix}\\[1em]
\mathbf b &= \begin{bmatrix}0 \\ 4 \\ -4\end{bmatrix}
\end{aligned}
$$

### augmented matrix


$$
\left[
\begin{array}{rrr|r}
3 & 4 & -1&0\\
0 & 1 & 1&4\\
0 & -1 & -1&-4
\end{array}
\right]
$$

## elimination step


$$
\left[
\begin{array}{rrr|r}
3 & 0 & -5&-16\\
0 & 1 & 1&4\\
0 & 0 & 0&0
\end{array}
\right]
$$

## dividing by the pivots


$$
\left[
\begin{array}{rrr|r}
1 & 0 & -\frac{5}{3}&-\frac{16}{3}\\
0 & 1 & 1&4\\
0 & 0 & 0&0
\end{array}
\right]
$$

The set of solutions obtained this way is

$$
\begin{aligned}
x &= \frac{5}{3}z - \frac{16}{3}\\
y &= 4-z\\
z &\in \mathbb R
\end{aligned}
$$